export const PAYMENT_CONFIG_REQUEST = "PAYMENT_CONFIG_REQUEST";
export const PAYMENT_CONFIG_SUCCESS = "PAYMENT_CONFIG_SUCCESS";
export const PAYMENT_CONFIG_FAIL = "PAYMENT_CONFIG_FAIL";

export const ADMIN_PAYMENT_SETTINGS_REQUEST = "ADMIN_PAYMENT_SETTINGS_REQUEST";
export const ADMIN_PAYMENT_SETTINGS_SUCCESS = "ADMIN_PAYMENT_SETTINGS_SUCCESS";
export const ADMIN_PAYMENT_SETTINGS_FAIL = "ADMIN_PAYMENT_SETTINGS_FAIL";

export const UPDATE_PAYMENT_SETTINGS_REQUEST = "UPDATE_PAYMENT_SETTINGS_REQUEST";
export const UPDATE_PAYMENT_SETTINGS_SUCCESS = "UPDATE_PAYMENT_SETTINGS_SUCCESS";
export const UPDATE_PAYMENT_SETTINGS_RESET = "UPDATE_PAYMENT_SETTINGS_RESET";
export const UPDATE_PAYMENT_SETTINGS_FAIL = "UPDATE_PAYMENT_SETTINGS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
